# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: textdiffusion/v1/textdiffusion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'textdiffusion/v1/textdiffusion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$textdiffusion/v1/textdiffusion.proto\x12\x10textdiffusion.v1\"\x15\n\x06Tokens\x12\x0b\n\x03ids\x18\x01 \x03(\r\"\xce\x01\n\x0fGenerateRequest\x12/\n\rprompt_tokens\x18\x01 \x01(\x0b\x32\x18.textdiffusion.v1.Tokens\x12\x19\n\x11max_output_tokens\x18\x02 \x01(\x05\x12\x11\n\tnum_steps\x18\x03 \x01(\x05\x12\x0c\n\x04seed\x18\x04 \x01(\x04\x12\x0f\n\x07mask_id\x18\x05 \x01(\r\x12\x14\n\x0c\x62lock_length\x18\x06 \x01(\x05\x12\x13\n\x0btemperature\x18\x07 \x01(\x02\x12\x12\n\nrequest_id\x18\x08 \x01(\t\"\x8e\x01\n\x10GenerateResponse\x12/\n\routput_tokens\x18\x01 \x01(\x0b\x32\x18.textdiffusion.v1.Tokens\x12\x35\n\rfinish_reason\x18\x02 \x01(\x0e\x32\x1e.textdiffusion.v1.FinishReason\x12\x12\n\nrequest_id\x18\x03 \x01(\t*(\n\x0c\x46inishReason\x12\x18\n\x14\x46INISH_REASON_LENGTH\x10\x00\x32j\n\x15TextGenerationService\x12Q\n\x08Generate\x12!.textdiffusion.v1.GenerateRequest\x1a\".textdiffusion.v1.GenerateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'textdiffusion.v1.textdiffusion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FINISHREASON']._serialized_start=435
  _globals['_FINISHREASON']._serialized_end=475
  _globals['_TOKENS']._serialized_start=58
  _globals['_TOKENS']._serialized_end=79
  _globals['_GENERATEREQUEST']._serialized_start=82
  _globals['_GENERATEREQUEST']._serialized_end=288
  _globals['_GENERATERESPONSE']._serialized_start=291
  _globals['_GENERATERESPONSE']._serialized_end=433
  _globals['_TEXTGENERATIONSERVICE']._serialized_start=477
  _globals['_TEXTGENERATIONSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
