python3 generate_llada.py \
  --mlp_ratio 4 \
  --d_model 4096 \
  --n_heads 32 \
  --rope_theta 10000.0 \
  --max_sequence_length 1024 \
  --vocab_size 126464 \
  --n_layers 32 \
  --device "cuda" \
  --ckpt_path model.safetensors \
  --vocab_path ./vocab.json \
  --merges_path ./merges.txt \
  --special_tokens ./special_tokens.json \
  --prompt "Oh wow, it's Judy!" \
  --mask_id 126336 \
  --steps 128 \
  --gen_length 128 \
  --block_length 32 \
  --temperature 0.0